name: Continuous Deployment
on:
  push:
    branches: ['**']
jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: yarn test
